#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."
uv run python -m grpc_tools.protoc \
  -I proto \
  --python_out=generated \
  --grpc_python_out=generated \
  proto/speaker.proto
# Fix bare import generated by grpc_tools for package use
sed -i '' 's/^import speaker_pb2/from generated import speaker_pb2/' generated/speaker_pb2_grpc.py
echo "Generated: generated/speaker_pb2.py  generated/speaker_pb2_grpc.py"
